// orchestrator.js - Master orchestrator for all agents
import { exec } from 'child_process';
import cron from 'node-cron';
import fs from 'fs';

// ============================================
// SCHEDULE CONFIGURATION
// ============================================
const SCHEDULES = {
    'sales-agent': '0 9 * * *',      // Daily at 9 AM
    'content-generator': '0 */4 * * *', // Every 4 hours
    'email-writer': '0 */2 * * *',     // Every 2 hours
    'social-media': '0 */2 * * *',     // Every 2 hours
    'revenue-pipeline': '0 */2 * * *', // Every 2 hours
    'daily-report': '0 18 * * *'       // Daily at 6 PM
};

// ============================================
// RUN AGENT
// ============================================
function runAgent(agentName, scriptPath) {
    console.log(`🔄 Running ${agentName}...`);
    exec(`node ${scriptPath}`, (error, stdout, stderr) => {
        if (error) {
            console.error(`❌ ${agentName} error:`, error.message);
            return;
        }
        console.log(`✅ ${agentName} completed`);
        if (stdout) console.log(stdout);
    });
}

// ============================================
// SCHEDULE ALL AGENTS
// ============================================
function scheduleAll() {
    console.log('⏰ Scheduling all agents...');
    
    // Sales agent
    cron.schedule(SCHEDULES['sales-agent'], () => {
        runAgent('Sales Agent', '../slideshow-kit/autonomous-sales-agent.js');
    });
    
    // Revenue pipeline
    cron.schedule(SCHEDULES['revenue-pipeline'], () => {
        runAgent('Revenue Pipeline', 'autonomous-pipeline.js');
    });
    
    // Daily report
    cron.schedule(SCHEDULES['daily-report'], () => {
        console.log('📊 Generating daily revenue report...');
        // This will be generated by the pipeline
    });
    
    console.log('✅ All agents scheduled');
    console.log('📋 Sales Agent: Daily at 9 AM');
    console.log('💰 Revenue Pipeline: Every 2 hours');
    console.log('📊 Daily Report: 6 PM');
}

// ============================================
// START
// ============================================
console.log('🚀 Sovereign Empire Orchestrator Starting...');
console.log('='.repeat(40));

// Run pipeline immediately on startup
console.log('🔄 Running initial revenue pipeline...');
setTimeout(() => {
    runAgent('Revenue Pipeline (Initial)', 'autonomous-pipeline.js');
}, 2000);

// Schedule everything
scheduleAll();

console.log('');
console.log('✅ Orchestrator running 24/7');
console.log('📊 Check reports/ for daily updates');
console.log('💰 Check pipeline-state.json for revenue tracking');